### ISSUE TITLE
is there any chance in merging this into openbox?

### ISSUE THREAD

**Issue by simonsmiley** [BurntSushi/openbox-multihead#2]
I would love to use this, but I really want to run software that is being maintained. Do you know anything about whether upstream is willing to merge these changes in?

**Comment by BurntSushi** [comment]
There is absolutely no way this will ever be merged upstream. Independent workspaces break a fundamental invariant of FreeDeskstop (EWMH) standards: that one and only one workspace is visible at a time. This has real world implications, e.g., pagers and panels will fail in surprising and strange ways.

You might say, "well it could just be an option that could be enabled and is disabled by default." I'd say that this is a >1000 line diff that makes pervasive changes to the way Openbox handles workspaces and monitors. Moreover, the code is probably buggy.

You may instead be interested in the WM I use now that replaced my use of Openbox Multihead: https://github.com/BurntSushi/wingo
