### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by aspiers** [BurntSushi/openbox-multihead#3]
Looks like there were no updates in many years - I guess the enhancements never got merged upstream and the fork got left behind?

**Comment by BurntSushi** [comment]
The last commit was eight years ago. I think that should answer your question.

> I guess the enhancements never got merged upstream and the fork got left behind?

They were never intended to get merged upstream.

**Comment by BurntSushi** [comment]
I wrote my own WM to address the same kinds of problems I was trying to solve with openbox-multihead: https://github.com/BurntSushi/wingo

**Comment by aspiers** [comment]
[**@BurntSushi**](https://github.com/BurntSushi) commented on [June 12, 2020 7:17 PM](https://github.com/BurntSushi/openbox-multihead/issues/3#issuecomment-643418722 "2020-06-12T18:17:08Z - Replied by Github Reply Comments"):
> The last commit was eight years ago. I think that should answer your question.
> 
> > I guess the enhancements never got merged upstream and the fork got left behind?
> 
> They were never intended to get merged upstream.

OK thanks.  I recommend updating the README to make this clearer.

> I wrote my own WM to address the same kinds of problems I was trying to solve with openbox-multihead: [BurntSushi/wingo](https://github.com/BurntSushi/wingo)

That's impressive!  Looks very nice indeed.  I would consider using it, but unfortunately the WM is such a critical part of my toolbox that I really need to use one which is actively maintained and has a decent community around it; I'm too busy to have time to switch WMs more than once every few years, so it has to be a strategic choice.  I don't find i3 great out of the box, but it has a good community and it looks like I can probably get it into decent shape with a bunch of customisation and extra hacks.

**Comment by BurntSushi** [comment]
I don't have the time or motivation to update every README of every project that I've ever published that is now dead. Sorry. Folks will have to come to that conclusion on their own based on available signals.
